//navbar data
export const NavData = [
  "Home",
  "light box",
  "3d signs",
  "Neons",
  "About",
  "Enquiry",
  "Aftersales Contact",
];
export const countriesWithCurrency = [
  "US-$ | United States",
  "CA-$ | Canada",
  "GB-£ | United Kingdom",
  "EU-€ | European Union",
  "JP-¥ | Japan",
  "CN-¥ | China",
  "IN-₹ | India",
  "AU-$ | Australia",
  "NZ-$ | New Zealand",
  "CH-CHF | Switzerland",
  "SE-kr | Sweden",
  "NO-kr | Norway",
  "DK-kr | Denmark",
  "SG-$ | Singapore",
  "HK-$ | Hong Kong",
  "KR-₩ | South Korea",
  "RU-₽ | Russia",
  "BR-R$ | Brazil",
  "MX-$ | Mexico",
  "ZA-R | South Africa",
  "AE-د.إ | United Arab Emirates",
  "SA-﷼ | Saudi Arabia",
  "IL-₪ | Israel",
  "TR-₺ | Turkey",
  "TH-฿ | Thailand",
  "MY-RM | Malaysia",
  "ID-Rp | Indonesia",
  "PH-₱ | Philippines",
  "VN-₫ | Vietnam",
  "NG-₦ | Nigeria",
];
export const test_data_cart = [
  { id: 1, item: "egg", price: 2000, quant: 0 },
  { id: 2, item: "Apple", price: 20, quant: 0},
  { id: 4, item: "Chiken", price: 4000, quant: 0 },
  { id: 5, item: "Chiken", price: 4000, quant: 0  },
  { id: 6, item: "Chiken", price: 4000, quant: 0 },
  { id: 7, item: "Chiken", price: 4000, quant: 0 },
  { id: 8, item: "Chiken", price: 4000, quant: 0 },
  { id: 9, item: "Chiken", price: 4000, quant: 0 },
];
